project_id = "rdjtjzhulroqioyviaiw"

[functions.check-ecocash-status]
verify_jwt = false

[functions.purchase-voucher]
verify_jwt = false

[functions.ecocash-callback]
verify_jwt = false

[functions.initiate-ecocash-payment]
verify_jwt = false
